### PR TITLE
Added Github Command

### PR DESCRIPTION
**Pull request by FC5570**
Added a github command which allows users to check the info of a github repository by providing the repo owner and the repo name separated by a "|". Also used the `verbose` option in Listeners/Cooldown.js line 25.

### CODE REVIEW

**Comment by FC5570** [comment]
Changed the separator to "/" instead of "|". Why salvage

**Comment by Milo123459** [comment]
> Changed the separator to "/" instead of "|". Why salvage

Why? You don't do https://github.com/Shamil-FD|ToastyXD you do https://github.com/Shamil-FD/ToastyXD

**Comment by FC5570** [comment]
hmm ok

**Comment by Milo123459** [comment]
Please run `yarn lint`

**Comment by FC5570** [comment]
um alright

**Comment by FC5570** [comment]
Ive already linted it tho

**Comment by FC5570** [comment]
done @Milo123459

**Comment by Milo123459** [comment]
:shipit: LGTM.

**Pull request merged**
